const PLANETS = [
  {
    name: 'mercury',
    orbitRate: 5,
    rotationRate: 0.01,
    distanceFromSun: 13,
    size: 1,
    amountOfSegments: 100,
  },
  {
    name: 'venus',
    orbitRate: 4,
    rotationRate: 0.02,
    distanceFromSun: 23,
    size: 2.2,
    amountOfSegments: 100,
  },
  {
    name: 'earth',
    orbitRate: 3,
    rotationRate: 0.02,
    distanceFromSun: 30,
    size: 2.5,
    amountOfSegments: 100,
  },
  {
    name: 'mars',
    orbitRate: 2.5,
    rotationRate: 0.02,
    distanceFromSun: 38,
    size: 1.5,
    amountOfSegments: 100,
  },
  {
    name: 'jupiter',
    orbitRate: 2,
    rotationRate: 0.02,
    distanceFromSun: 60,
    size: 4.2,
    amountOfSegments: 100,
  },
  {
    name: 'saturn',
    orbitRate: 1,
    rotationRate: 0.02,
    distanceFromSun: 75,
    size: 3.7,
    amountOfSegments: 100,
  },
  {
    name: 'uranus',
    orbitRate: 0.7,
    rotationRate: 0.02,
    distanceFromSun: 88,
    size: 2.2,
    amountOfSegments: 100,
  },
  {
    name: 'neptune',
    orbitRate: 0.5,
    rotationRate: 0.02,
    distanceFromSun: 100,
    size: 2.2,
    amountOfSegments: 100,
  },
];

export default PLANETS;
